config/routes.rb
Rails.application.routes.draw do
  resources :books

  get 'git_http/show'

  resources :widgets

  get 'models_need_dots/show'

  get 'taco_order/edit'

  get 'hello_angular/show'

  resources :pages
  root 'pages#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/widget.rb
class Widget < ActiveRecord::Base

  validates :price, presence: true, numericality: { greater_than: 10 }
  validates :name, presence: true, length: { minimum: 7 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.all

    respond_to do |format|
      format.html {
        @books_json = @books.map{ |b| BookSerializer.new(b).serializable_hash }
        @urls = {
          books: books_path
        }
      }
      format.json { render json: @books }
    end
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.'}
        format.json { render json: @book }
      else
        format.html {render :new}
        format.json {render json: @book.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /books/1
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html{ redirect_to @book, notice: 'Book was successfully updated.'}
        format.json{ render json: @book }
      else
        format.html{ render :edit }
        format.json{ render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { render json: {message: "Book was deleted"}}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/git_http_controller.rb
class GitHttpController < ApplicationController
  def show
  end
end

app/controllers/hello_angular_controller.rb
class HelloAngularController < ApplicationController
  def show
  end
end

app/controllers/models_need_dots_controller.rb
class ModelsNeedDotsController < ApplicationController
  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/taco_order_controller.rb
class TacoOrderController < ApplicationController
  def edit
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  def create
    @widget = Widget.new(widget_params)

    if @widget.save
      redirect_to @widget, notice: 'Widget was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /widgets/1
  def update
    if @widget.update(widget_params)
      redirect_to @widget, notice: 'Widget was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /widgets/1
  def destroy
    @widget.destroy
    redirect_to widgets_url, notice: 'Widget was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def widget_params
      params.require(:widget).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h2>Books::</h2>


<div ng-app="AngulaRails" ng-controller="BooksController" ng-init="urls=<%=@urls.to_json %>; books=<%= @books_json.to_json %>">
  <div class="row">
    <div class="col-md-6">

      <form ng-submit="save()">
        <div class="form-group">
          <label>Title</title>
          <input type="text" class="form-control" ng-model="book.title">
        </div>

        <div class="form-group">
          <label>Author</title>
          <input type="text" class="form-control" ng-model="book.author">
        </div>

        <button class="btn btn-info">
          Save
        </button>
      </form> 


      <p>&nbsp;</p>

      <div>
      <ul>
        <li ng-repeat="book in books">
        <div class="btn btn-default" ng-click="edit(book)">
          <i class="icon-pencil" /> 
        </div>

        <div class="btn btn-default" ng-click="delete(book)"> 
          <i class="icon-trash" />
        </div>

          {{ book.title }} by {{ book.author }}
        </li>
      </ul>
      </div>

    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/git_http/show.html.haml
.row{"ng-app" => "AngulaRails", "ng-controller" => "GitHttpController"}
  .alert.alert-danger{"ng-show" => "errorMessage"}
    %strong Error!

    %i.icon-warning-sign

  %h1 GitHttp

  .col-md-6
    %form{"ng-submit" => "search()"}
      .input-group
        %span.input-group-addon
          %i.icon-search
        %input.form-control{"ng-model" => "username", placeholder: "Git Username", type: "text"}/

  %i.icon-refreshicon-spin{"ng-show" => "searching"}
  %span.icon-refreshicon-spin{"ng-show" => "searching"} loading...

  %div{"ng-show" => "repo_size"}
    Number of Repos:
    %span{"ng-show" => "repo_size"}

  %ul.list-group
    %li.list-group-item{"ng-repeat" => "repo in repos"}
      %h4.list-group-item-heading
      %p.list-group-item-text.text-muted

app/views/hello_angular/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="HelloWorldController">
  <div class="col-md-6">
  <h1>Hello AngularJS</h1>
  <p>Type in the input box and watch as AngularJS updates the property through \ themagicofbinding.</p>
  <input type="text" class="form-control" ng-model="myText" >
  {{ myText }}
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPEhtml>
<htmllang="en"> <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <title><%= content_for?(:title) ? yield(:title) : "Angularails" %></title> 
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  </head>

  <body>

    <%= render 'shared/header' %>

    <!-- <div class="navbar navbar&#45;inverse">  -->
    <!--   <div class="container"> -->
    <!--     <a class="navbar&#45;brand" href="#">Angularails</a> -->
    <!--   </div> -->
    <!-- </div> -->

    <div class="container"> 
      <%= yield %>
    </div>

  </body>
</html>

app/views/models_need_dots/show.html.erb
<h1>ModelsNeedDots#show</h1>
<p>Find me in app/views/models_need_dots/show.html.erb</p>


<div ng-app="AngulaRails" ng-controller="ModelsNeedDotsController">

  <div class="row">

    <div class="col-md-12">

      <h1>Oh ho</h1>
      Message is {{ someModel.message }}
      <input type='text' ng-model="someModel.message" class="form-control">

      <ul class="list-unstyled">
        <li ng-repeat="s in stuff" style="margin-top: 10px">
          Message is {{ someModel.message }}
          <input type='text' ng-model="someModel.message" class="form-control">
        </li>
      </ul>

    </div>

  </div>
</div>

app/views/pages/index.html.haml
%h2
  Index::


%ul
  %li
  %li
    = link_to 'Git Http', git_http_show_path
  %li
    =link_to 'Books', books_path

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: pages_path} AngularPractice::
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          %a{href: pages_path} Home
        %li
          %a{href: "#about"} About
        %li
          %a{href: "#contact"} Contact
      %ul.nav.navbar-nav.navbar-right
        /
          <li><a href="../navbar/">Default</a></li>
          <li><a href="../navbar-static-top/">Static top</a></li>
          <li class="active"><a href="./">Fixed top</a></li>
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{role: "menu"}
            %li.dropdown-header Nav header
            %li
              %a{href: "#"} Profile
            %li.divider
            %li
              %a{href: "#"} Sign Out
    / /.nav-collapse

app/views/taco_order/edit.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="TacoOrderController">
  <div class="col-md-6">
    <h3>Add Taco to Order</h3>

    <form ng-submit="addTaco()">
      <div class="form-group">
        <label for="name">Name your creation</label>
        <input type="text" class="form-control" placeholder="Super Tasy" ng-model="taco.name"></input>
      </div>

      <div class="form-group">
        <label for="filling">Select your filling</label>
        <select ng-model="taco.filling" class="form-control" ng-options="f.id as f.name for f in fillings"> </select>
      </div>

      <div class="form-group">
        <label>Extras</label>

        <div class="checkbox" ng-repeat="extra in extras">
          <label>
            <input type="checkbox" ng-model="extra.checked"></input>
            {{ extra.name }}
          </label>
        </div>
      </div>


      <div class="form-group"> 
        <label>Cheese</label>
        <div class="radio">
          <label>
            <input type="radio" value="No Cheese" ng-model="taco.cheese"></input> No Cheese
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" value="Normal Cheese" ng-model="taco.cheese"></input>
            Normal Cheese
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" value="Mucho Queso" ng-model="taco.cheese"></input>
            Mucho Queso
          </label>
        </div>
      </div>


      <button class="btn btn-primary">
        Submit
      </button>
    </form>

  </div>

  <div class="col-md-6">
    <h3>Your Order</h3>
    <table class="table">
      <tbody>
        <tr ng-repeat="taco in tacos">
          <td>{{ taco.name }}</td>
          <td>{{ taco.filling }}</td>
          <td>
            <span ng-repeat="extra in taco.extras">
              {{extra}}
            </span>
          </td>
          <td>{{ taco.cheese }}</td>
        </tr>
      </tbody>
    </table>

  </div>
</div>

app/views/widgets/_form.html.erb
<div ng-app="AngulaRails">

  <%= form_for @widget, html: { name: "widgetForm", "novalidate" => true } do |f| %>
    <% if @widget.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

        <ul>
          <% @widget.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[name]'].$invalid }">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control", "ng-model" => "name", required: true, "ng-minlength"=>"7" %>
      <span class="help-block" ng-show="widgetForm['widget[name]'].$error.required">Required</span>
    </div>

    <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[price]'].$invalid }">
      <%= f.label :price %><br>
      <%= f.number_field :price, class: "form-control", "ng-model" => "price", required: true,"min"=>"10" %>
      <span class="help-block" ng-show="widgetForm['widget[price]'].$error.required">A number is required</span>
      <span class="help-block" ng-show="widgetForm['widget[price]'].$error.min">Most be greater than 10</span>
    </div>

    <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary", "ng-disabled" => "widgetForm.$invalid" %>
    </div>
  <% end %>

</div>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.price %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @widget.price %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>